openapi: 3.0.2

info:
  title: Eclipse Kapua REST API - Device Management - Asset
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  schemas:
    deviceAssetDefinition:
      allOf:
        - $ref: '#/components/schemas/assetDescription'
        - type: object
          properties:
            channels:
              type: array
              items:
                $ref: '#/components/schemas/channelDefinition'
            name:
              type: string
          example:
            name: asset1
            channels:
              - valueType: integer
                name: Channel-1
                mode: READ
              - valueType: integer
                name: Channel-2
                mode: WRITE
              - valueType: integer
                name: Channel-3
                mode: READ_WRITE
    deviceAssetValue:
      allOf:
        - $ref: '#/components/schemas/assetDescription'
        - type: object
          properties:
            channels:
              type: array
              items:
                $ref: '#/components/schemas/channelValue'
            name:
              type: string
          example:
            name: asset2
            channels:
              - valueType: integer
                value: 5
                name: Channel-1
                timestamp: '2019-09-12T14:50:24.446Z'
              - valueType: integer
                value: 8
                name: Channel-3
                timestamp: '2019-09-12T14:50:24.446Z'
    deviceAssetDefinitions:
      description: A list container for the Assets of a Device
      type: object
      properties:
        deviceAsset:
          type: array
          items:
            $ref: '#/components/schemas/deviceAssetDefinition'
      example:
        type: deviceAssets
        deviceAsset:
          - name: asset1
            channels:
              - valueType: integer
                name: Channel-1
                mode: READ
              - valueType: integer
                name: Channel-2
                mode: WRITE
              - valueType: integer
                name: Channel-3
                mode: READ_WRITE
          - name: asset2
            channels:
              - valueType: integer
                name: Channel-1
                mode: READ
              - valueType: integer
                name: Channel-2
                mode: WRITE
              - valueType: integer
                name: Channel-3
                mode: READ_WRITE
    deviceAssetValues:
      description: A list container for the Assets of a Device
      type: object
      properties:
        deviceAsset:
          items:
            type: array
            items:
              $ref: '#/components/schemas/deviceAssetValue'
      example:
        type: deviceAssets
        deviceAsset:
          - name: asset2
            channels:
              - valueType: integer
                value: 5
                name: Channel-1
                timestamp: '2019-09-12T14:50:24.446Z'
              - valueType: integer
                value: 8
                name: Channel-3
                timestamp: '2019-09-12T14:50:24.446Z'
    channelDefinition:
      allOf:
        - $ref: '#/components/schemas/assetDescription'
        - type: object
          properties:
            mode:
              type: string
              enum:
                - READ
                - WRITE
                - READ_WRITE
            name:
              type: string
            valueType:
              type: string
          example:
            valueType: integer
            name: Channel-1
            mode: READ
    channelValue:
      allOf:
        - $ref: '#/components/schemas/assetDescription'
        - type: object
          properties:
            name:
              type: string
            valueType:
              type: string
            value:
              type: string
            timestamp:
              type: string
              format: 'date-time'
          example:
            valueType: integer
            value: 5
            name: Channel-1
            timestamp: '2019-09-12T14:50:24.446Z'
    assetDescription:
      description: |
        An **Asset**, as defined in Kura, is a logical representation of a field device, described by a list of **Channels**.
        The Asset uses a specific Driver instance to communicate with the underlying device and it models a generic device resource as a Channel.
        A register in a PLC or a GATT Characteristic in a Bluetooth device are examples of Channels.
        In this way, each Asset has multiple Channels for reading and writing data from/to an Industrial Device.
